from __future__ import annotations
import base64, shutil
from datetime import datetime
from pathlib import Path

TARGET="alliance_exception_forensics_v424.py"
REG="alliance_optional_property_modules.py"
DATA="ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwppbXBvcnQgaHRtbCwganNvbgpmcm9tIGZhc3RhcGkucmVzcG9uc2VzIGltcG9ydCBIVE1MUmVzcG9uc2UKZnJvbSBzcWxhbGNoZW15IGltcG9ydCB0ZXh0CgppbXBvcnQgYWxsaWFuY2VfcHJvcGVydHlfYnJhaW5fZm91bmRhdGlvbl92MSBhcyBmb3VuZGF0aW9uCmltcG9ydCBhbGxpYW5jZV9jcmVfY2hhbXBpb25zaGlwX3Y0MTAgYXMgdjQxMAppbXBvcnQgYWxsaWFuY2VfYXV0b21hdGlvbl90cnV0aF9lc2NhbGF0b3JfdjQyMSBhcyB2NDIxCmltcG9ydCBhbGxpYW5jZV9hdXRvbWF0aW9uX2Nsb3N1cmVfdjQyMiBhcyB2NDIyCmltcG9ydCBhbGxpYW5jZV9hdXRvbWF0aW9uX2dyYW1tYXJfcmVzY3VlX3Y0MjMgYXMgdjQyMwoKVkVSU0lPTj0iNC4yLjQuMS1BTExJQU5DRS1FWENFUFRJT04tRk9SRU5TSUNTLUhPVEZJWCIKTU9ERT0iUkVBRF9PTkxZX0ZPUkVOU0lDU19TQ0hFTUFfSE9URklYX1Y0MjFfQ09OU0VOU1VTX0NPTFVNTiIKRVhBTV9WRVJTSU9OPXY0MTAuRVhBTV9WRVJTSU9OCgpkZWYgX2VuZ2luZShjb3JlKTogcmV0dXJuIGZvdW5kYXRpb24uX2VuZ2luZV9mcm9tX2NvcmUoY29yZSkKZGVmIF9hcHAoY29yZSk6IHJldHVybiBnZXRhdHRyKGNvcmUsImFwcCIsTm9uZSkgb3IgY29yZQoKZGVmIGluc3BlY3QoZW5naW5lKToKICAgIHY0MjMucnVuKGVuZ2luZSkKICAgIHdpdGggZW5naW5lLmNvbm5lY3QoKSBhcyBjOgogICAgICAgIHJvd3M9W2RpY3QocikgZm9yIHIgaW4gYy5leGVjdXRlKHRleHQoIiIiCiAgICAgICAgU0VMRUNUIGMuYXVkaXRfaWQsYy5vcmRpbmFsLGMucmF3X3RleHQsCiAgICAgICAgICAgICAgIGMucHJlZGljdGVkX2NsYXNzLGMucHJlZGljdGVkX3RyYW5zYWN0aW9uLGMucHJlZGljdGVkX293bmVyc2hpcCwKICAgICAgICAgICAgICAgYy5wcmVkaWN0aW9uX2NvbmZpZGVuY2UsYy5wcmVkaWN0aW9uX3J1bGUsCiAgICAgICAgICAgICAgIGEuc3RhdHVzIGFfc3RhdHVzLGEudHJ1dGhfY2xhc3MgYV9jbGFzcyxhLnRydXRoX3RyYW5zYWN0aW9uIGFfdHgsYS50cnV0aF9vd25lcnNoaXAgYV9vd24sYS5jb25zZW5zdXMgYV9ldmlkZW5jZSwKICAgICAgICAgICAgICAgei5zdGF0dXMgel9zdGF0dXMsei50cnV0aF9jbGFzcyB6X2NsYXNzLHoudHJ1dGhfdHJhbnNhY3Rpb24gel90eCx6LnRydXRoX293bmVyc2hpcCB6X293bix6LmV2aWRlbmNlIHpfZXZpZGVuY2UsCiAgICAgICAgICAgICAgIHIuc3RhdHVzIHJfc3RhdHVzLHIudHJ1dGhfY2xhc3Mgcl9jbGFzcyxyLnRydXRoX3RyYW5zYWN0aW9uIHJfdHgsci50cnV0aF9vd25lcnNoaXAgcl9vd24sci5ldmlkZW5jZSByX2V2aWRlbmNlCiAgICAgICAgRlJPTSBhbGxpYW5jZV9jaGFtcGlvbnNoaXBfdjQxMF9jYXNlcyBjCiAgICAgICAgTEVGVCBKT0lOIGFsbGlhbmNlX2F1dG9tYXRpb25fdjQyMV90cnV0aCBhIE9OIGEuYXVkaXRfaWQ9Yy5hdWRpdF9pZAogICAgICAgIExFRlQgSk9JTiBhbGxpYW5jZV9hdXRvbWF0aW9uX3Y0MjJfdHJ1dGggeiBPTiB6LmF1ZGl0X2lkPWMuYXVkaXRfaWQKICAgICAgICBMRUZUIEpPSU4gYWxsaWFuY2VfYXV0b21hdGlvbl92NDIzX3RydXRoIHIgT04gci5hdWRpdF9pZD1jLmF1ZGl0X2lkCiAgICAgICAgV0hFUkUgYy5leGFtX3ZlcnNpb249OmUKICAgICAgICBPUkRFUiBCWSBjLm9yZGluYWwKICAgICAgICAiIiIpLHsiZSI6RVhBTV9WRVJTSU9OfSkubWFwcGluZ3MoKV0KICAgIHVucmVzb2x2ZWQ9W10KICAgIGZvciB4IGluIHJvd3M6CiAgICAgICAgaWYgeFsiYV9zdGF0dXMiXT09IkFVVE9fUkVTT0xWRUQiIG9yIHhbInpfc3RhdHVzIl09PSJBVVRPX1JFU09MVkVEIiBvciB4WyJyX3N0YXR1cyJdPT0iQVVUT19SRVNPTFZFRCI6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgcmF3PXhbInJhd190ZXh0Il0gb3IgIiIKICAgICAgICB1bnJlc29sdmVkLmFwcGVuZCh7CiAgICAgICAgICAgICJhdWRpdF9pZCI6c3RyKHhbImF1ZGl0X2lkIl0pLAogICAgICAgICAgICAib3JkaW5hbCI6eFsib3JkaW5hbCJdLAogICAgICAgICAgICAicmF3X3RleHQiOnJhdywKICAgICAgICAgICAgInN0dWRlbnRfZnJvemVuX3ByZWRpY3Rpb24iOnsKICAgICAgICAgICAgICAgICJjbGFzcyI6eFsicHJlZGljdGVkX2NsYXNzIl0sCiAgICAgICAgICAgICAgICAidHJhbnNhY3Rpb24iOnhbInByZWRpY3RlZF90cmFuc2FjdGlvbiJdLAogICAgICAgICAgICAgICAgIm93bmVyc2hpcCI6eFsicHJlZGljdGVkX293bmVyc2hpcCJdLAogICAgICAgICAgICAgICAgImNvbmZpZGVuY2UiOmZsb2F0KHhbInByZWRpY3Rpb25fY29uZmlkZW5jZSJdIG9yIDApLAogICAgICAgICAgICAgICAgInJ1bGUiOnhbInByZWRpY3Rpb25fcnVsZSJdLAogICAgICAgICAgICB9LAogICAgICAgICAgICAidjQyMSI6ewogICAgICAgICAgICAgICAgInN0YXR1cyI6eFsiYV9zdGF0dXMiXSwKICAgICAgICAgICAgICAgICJ0cnV0aCI6W3hbImFfY2xhc3MiXSx4WyJhX3R4Il0seFsiYV9vd24iXSwKICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAiZXZpZGVuY2UiOnhbImFfZXZpZGVuY2UiXSwKICAgICAgICAgICAgfSwKICAgICAgICAgICAgInY0MjIiOnsKICAgICAgICAgICAgICAgICJzdGF0dXMiOnhbInpfc3RhdHVzIl0sCiAgICAgICAgICAgICAgICAidHJ1dGgiOlt4WyJ6X2NsYXNzIl0seFsiel90eCJdLHhbInpfb3duIl1dLAogICAgICAgICAgICAgICAgImV2aWRlbmNlIjp4WyJ6X2V2aWRlbmNlIl0sCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJ2NDIzIjp7CiAgICAgICAgICAgICAgICAic3RhdHVzIjp4WyJyX3N0YXR1cyJdLAogICAgICAgICAgICAgICAgInRydXRoIjpbeFsicl9jbGFzcyJdLHhbInJfdHgiXSx4WyJyX293biJdXSwKICAgICAgICAgICAgICAgICJldmlkZW5jZSI6eFsicl9ldmlkZW5jZSJdLAogICAgICAgICAgICB9LAogICAgICAgICAgICAiZnJlc2hfZGlhZ25vc3RpY3MiOnsKICAgICAgICAgICAgICAgICJ2NDIxX2V2aWRlbmNlX2p1ZGdlIjp2NDIxLmp1ZGdlX2V2aWRlbmNlKHJhdyksCiAgICAgICAgICAgICAgICAidjQyMV9jb3VudGVyZmFjdHVhbF9jcml0aWMiOnY0MjEuanVkZ2VfY3JpdGljKHJhdyksCiAgICAgICAgICAgICAgICAidjQyMl9zZW1hbnRpY190cnV0aCI6djQyMi5zZW1hbnRpY190cnV0aChyYXcpLAogICAgICAgICAgICAgICAgInY0MjNfZ3JhbW1hcl9qdWRnZV9vbmUiOnY0MjMuZ3JhbW1hcl9qdWRnZV9vbmUocmF3KSwKICAgICAgICAgICAgICAgICJ2NDIzX2dyYW1tYXJfanVkZ2VfdHdvIjp2NDIzLmdyYW1tYXJfanVkZ2VfdHdvKHJhdyksCiAgICAgICAgICAgICAgICAidjQyM19yZXNjdWVfdHJ1dGgiOnY0MjMucmVzY3VlX3RydXRoKHJhdyksCiAgICAgICAgICAgIH0KICAgICAgICB9KQogICAgcmV0dXJuIHsKICAgICAgICAidmVyc2lvbiI6VkVSU0lPTiwKICAgICAgICAiZXhhbV92ZXJzaW9uIjpFWEFNX1ZFUlNJT04sCiAgICAgICAgInVucmVzb2x2ZWRfY291bnQiOmxlbih1bnJlc29sdmVkKSwKICAgICAgICAiY2FzZXMiOmZvdW5kYXRpb24uX2pzb25fc2FmZSh1bnJlc29sdmVkKSwKICAgICAgICAibmV4dF9zdGVwIjoiVXNlIHRoaXMgcmVhZC1vbmx5IGZvcmVuc2ljIHBhY2tldCB0byBidWlsZCBhIGdlbmVyaWMgYXV0b21hdGVkIHJlc29sdmVyLiBEbyBub3QgbWFudWFsbHkgbGFiZWwgdGhlIGNhc2UuIiwKICAgICAgICAic2FmZXR5Ijp7InN0dWRlbnRfdHVuaW5nIjowLCJwcm9kdWN0aW9uX3dyaXRlcyI6MCwid2hhdHNhcHBfd3JpdGVzIjowLCJnb2xkX211dGF0aW9ucyI6MH0KICAgIH0KCmRlZiBfZGFzaGJvYXJkKGVuZ2luZSk6CiAgICBkYXRhPWluc3BlY3QoZW5naW5lKQogICAgcmV0dXJuIGYiIiI8IWRvY3R5cGUgaHRtbD48aHRtbD48aGVhZD48bWV0YSBjaGFyc2V0PSd1dGYtOCc+CiAgICA8dGl0bGU+QWxsaWFuY2UgRXhjZXB0aW9uIEZvcmVuc2ljcyA0LjIuNDwvdGl0bGU+CiAgICA8c3R5bGU+Ym9keXt7Zm9udC1mYW1pbHk6QXJpYWw7bWFyZ2luOjMwcHg7YmFja2dyb3VuZDojZjZmN2ZiO2NvbG9yOiMxNzIwMzM7bWF4LXdpZHRoOjEyMDBweH19cHJle3t3aGl0ZS1zcGFjZTpwcmUtd3JhcDtiYWNrZ3JvdW5kOiMxMDE2MjQ7Y29sb3I6I2VlZjNmZjtwYWRkaW5nOjE4cHg7Ym9yZGVyLXJhZGl1czoxMnB4fX0ub2t7e2JhY2tncm91bmQ6I2U4ZjhlZTtwYWRkaW5nOjE0cHg7Ym9yZGVyLXJhZGl1czoxMHB4fX08L3N0eWxlPjwvaGVhZD48Ym9keT4KICAgIDxoMT5BbGxpYW5jZSBFeGNlcHRpb24gRm9yZW5zaWNzIDQuMi40PC9oMT4KICAgIDxwPlJlYWQtb25seSBmb3JlbnNpYyBwYWNrZXQgZm9yIG9ubHkgdGhlIGZpbmFsIHVucmVzb2x2ZWQgVjQgY2FzZShzKS4gRnJvemVuIHN0dWRlbnQgcmVtYWlucyB1bnRvdWNoZWQuPC9wPgogICAgPGRpdiBjbGFzcz0nb2snPlVucmVzb2x2ZWQgY2FzZXM6IDxiPntkYXRhWyJ1bnJlc29sdmVkX2NvdW50Il19PC9iPi4gTm8gbWFudWFsIGNsYXNzaWZpY2F0aW9uIHJlcXVlc3RlZC48L2Rpdj4KICAgIDxoMj5NYWNoaW5lIEZvcmVuc2ljIFJlcG9ydDwvaDI+CiAgICA8cHJlPntodG1sLmVzY2FwZShqc29uLmR1bXBzKGRhdGEsZW5zdXJlX2FzY2lpPUZhbHNlLGluZGVudD0yKSl9PC9wcmU+CiAgICA8L2JvZHk+PC9odG1sPiIiIgoKZGVmIHJlZ2lzdGVyKGNvcmUpOgogICAgZW5naW5lPV9lbmdpbmUoY29yZSk7IGFwcD1fYXBwKGNvcmUpCiAgICBpZiBub3QgZm91bmRhdGlvbi5fcm91dGVfZXhpc3RzKGFwcCwiL2FwaS9wcm9wZXJ0eS1icmFpbi9hdXRvbWF0aW9uLXY0MjQvc3RhdHVzIik6CiAgICAgICAgQGFwcC5nZXQoIi9hcGkvcHJvcGVydHktYnJhaW4vYXV0b21hdGlvbi12NDI0L3N0YXR1cyIpCiAgICAgICAgZGVmIHN0YXR1c192NDI0KCk6IHJldHVybiBpbnNwZWN0KGVuZ2luZSkKICAgIGlmIG5vdCBmb3VuZGF0aW9uLl9yb3V0ZV9leGlzdHMoYXBwLCIvcHJvcGVydHktYnJhaW4vYXV0b21hdGlvbi12NDI0Iik6CiAgICAgICAgQGFwcC5nZXQoIi9wcm9wZXJ0eS1icmFpbi9hdXRvbWF0aW9uLXY0MjQiLHJlc3BvbnNlX2NsYXNzPUhUTUxSZXNwb25zZSkKICAgICAgICBkZWYgcGFnZV92NDI0KCk6IHJldHVybiBIVE1MUmVzcG9uc2UoX2Rhc2hib2FyZChlbmdpbmUpKQogICAgcmV0dXJuIHsic3RhdHVzIjoiUkVHSVNURVJFRCIsInZlcnNpb24iOlZFUlNJT04sInJvdXRlIjoiL3Byb3BlcnR5LWJyYWluL2F1dG9tYXRpb24tdjQyNCIsCiAgICAgICAgICAgICJwb2xpY3kiOiJSRUFEX09OTFlfRVhDRVBUSU9OX0ZPUkVOU0lDUyIsInN0dWRlbnRfdHVuaW5nIjowLCJwcm9kdWN0aW9uX3dyaXRlcyI6MCwid2hhdHNhcHBfd3JpdGVzIjowLCJnb2xkX211dGF0aW9ucyI6MH0K"

def chk(p):
    compile(p.read_text(encoding="utf-8"), str(p), "exec")

def main():
    r=Path.cwd()
    required=[
        "alliance_exception_forensics_v424.py",
        "alliance_automation_grammar_rescue_v423.py",
        "alliance_automation_closure_v422.py",
        "alliance_automation_truth_escalator_v421.py",
        "alliance_automation_machine_v420.py",
        "alliance_cre_championship_v410.py",
        "alliance_cre_academy_v402.py",
        REG,
    ]
    missing=[x for x in required if not (r/x).exists()]
    if missing:
        raise SystemExit("Missing cumulative files: "+", ".join(missing))

    current=(r/TARGET).read_text(encoding="utf-8")
    if "a.evidence a_evidence" not in current and "a.consensus a_evidence" not in current:
        raise SystemExit("Unexpected v424 source shape. Refusing blind overwrite.")

    backup=r/f"{TARGET}.before-hotfix-{datetime.now().strftime('%Y%m%d-%H%M%S')}.bak"
    shutil.copy2(r/TARGET, backup)
    (r/TARGET).write_text(base64.b64decode(DATA).decode(), encoding="utf-8")

    chk(r/TARGET)
    chk(r/REG)

    text421=(r/"alliance_automation_truth_escalator_v421.py").read_text(encoding="utf-8")
    if "consensus JSONB" not in text421:
        raise SystemExit("v421 schema verification failed: consensus column not found.")
    if "a.consensus a_evidence" not in (r/TARGET).read_text(encoding="utf-8"):
        raise SystemExit("Hotfix verification failed.")

    print("Foundation 4.2.4.1 hotfix installed")
    print("Fixed: v421 truth uses consensus JSONB, not evidence JSONB")
    print("No database mutation required")
    print("Frozen V4 student unchanged")
    print("Production/WhatsApp/Gold writes: 0")
    print("Dashboard remains: /property-brain/automation-v424")
    print("Backup:", backup)

if __name__=="__main__":
    main()
