from __future__ import annotations
import base64, shutil
from datetime import datetime
from pathlib import Path

MODULE="alliance_v4_failure_forensics_v434f.py"
REG="alliance_optional_property_modules.py"
DATA="ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKaW1wb3J0IGh0bWwKaW1wb3J0IGpzb24KZnJvbSBmYXN0YXBpLnJlc3BvbnNlcyBpbXBvcnQgSFRNTFJlc3BvbnNlCgppbXBvcnQgYWxsaWFuY2VfcHJvcGVydHlfYnJhaW5fZm91bmRhdGlvbl92MSBhcyBmb3VuZGF0aW9uCmltcG9ydCBhbGxpYW5jZV9jcmVfYWNhZGVteV92NDAyIGFzIHY0MDIKaW1wb3J0IGFsbGlhbmNlX2F1dG9ub21vdXNfc3R1ZGVudF92NDMwIGFzIHY0MzAKaW1wb3J0IGFsbGlhbmNlX2F1dG9ub21vdXNfc3R1ZGVudF92NDMxIGFzIHY0MzEKaW1wb3J0IGFsbGlhbmNlX2F1dG9ub21vdXNfc3R1ZGVudF92NDMyIGFzIHY0MzIKaW1wb3J0IGFsbGlhbmNlX2F1dG9ub21vdXNfc3R1ZGVudF92NDMzIGFzIHY0MzMKaW1wb3J0IGFsbGlhbmNlX2F1dG9ub21vdXNfc3R1ZGVudF92NDM0IGFzIHY0MzQKClZFUlNJT04gPSAiNC4zLjRGLUFMTElBTkNFLVY0LUZBSUxVUkUtRk9SRU5TSUNTIgpNT0RFID0gIlJFQURfT05MWV9FWEFDVF9GQUlMVVJFX0ZPUkVOU0lDU19OT19TVFVERU5UX0NIQU5HRVNfTk9fVjVfRlJFRVpFIgoKZGVmIF9lbmdpbmUoY29yZSk6CiAgICByZXR1cm4gZm91bmRhdGlvbi5fZW5naW5lX2Zyb21fY29yZShjb3JlKQoKZGVmIF9hcHAoY29yZSk6CiAgICByZXR1cm4gZ2V0YXR0cihjb3JlLCAiYXBwIiwgTm9uZSkgb3IgY29yZQoKZGVmIF9zYWZlKHYpOgogICAgcmV0dXJuIGZvdW5kYXRpb24uX2pzb25fc2FmZSh2KQoKZGVmIF9wcmVkKGZuLCByYXcpOgogICAgdHJ5OgogICAgICAgIHAgPSBmbihyYXcpCiAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgImNsYXNzIjogcC5nZXQoImNsYXNzIiksCiAgICAgICAgICAgICJ0cmFuc2FjdGlvbiI6IHAuZ2V0KCJ0cmFuc2FjdGlvbiIpLAogICAgICAgICAgICAib3duZXJzaGlwIjogcC5nZXQoIm93bmVyc2hpcCIpLAogICAgICAgICAgICAiY29uZmlkZW5jZSI6IHAuZ2V0KCJjb25maWRlbmNlIiksCiAgICAgICAgICAgICJydWxlIjogcC5nZXQoInJ1bGUiKSwKICAgICAgICB9CiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICByZXR1cm4geyJlcnJvciI6IGYie3R5cGUoZXhjKS5fX25hbWVfX306IHtleGN9In0KCmRlZiBfZmFpbHVyZV9mYW1pbHkoZmllbGQsIHRydXRoLCBzdHVkZW50KToKICAgIGlmIGZpZWxkID09ICJjbGFzcyIgYW5kIHRydXRoID09ICJQUk9QRVJUWV9BVkFJTEFCSUxJVFkiIGFuZCBzdHVkZW50ID09ICJSRVFVSVJFTUVOVCI6CiAgICAgICAgcmV0dXJuICJERU1BTkRfT1ZFUkNMQUlNX09OX1BST1BFUlRZX09GRkVSIgogICAgaWYgZmllbGQgPT0gImNsYXNzIiBhbmQgdHJ1dGggPT0gIlJFUVVJUkVNRU5UIiBhbmQgc3R1ZGVudCA9PSAiUFJPUEVSVFlfQVZBSUxBQklMSVRZIjoKICAgICAgICByZXR1cm4gIk9GRkVSX0xFQUtBR0VfSU5UT19ERU1BTkQiCiAgICBpZiBmaWVsZCA9PSAidHJhbnNhY3Rpb24iIGFuZCB0cnV0aCA9PSAiVU5LTk9XTiIgYW5kIHN0dWRlbnQgPT0gIlJFTlQiOgogICAgICAgIHJldHVybiAiUkVOVF9SRUxBVElPTl9MRUFLQUdFIgogICAgaWYgZmllbGQgPT0gInRyYW5zYWN0aW9uIiBhbmQgdHJ1dGggPT0gIlJFTlQiIGFuZCBzdHVkZW50ID09ICJVTktOT1dOIjoKICAgICAgICByZXR1cm4gIk1JU1NFRF9SRU5UX1JFTEFUSU9OIgogICAgaWYgZmllbGQgPT0gInRyYW5zYWN0aW9uIiBhbmQgdHJ1dGggPT0gIlNBTEUiIGFuZCBzdHVkZW50ID09ICJVTktOT1dOIjoKICAgICAgICByZXR1cm4gIk1JU1NFRF9TQUxFX1JFTEFUSU9OIgogICAgcmV0dXJuICJPVEhFUiIKCmRlZiByZXBvcnQoZW5naW5lKToKICAgIHJvd3MgPSB2NDMwLl92NF90cnV0aF9yb3dzKGVuZ2luZSkKICAgIGZhaWx1cmVzID0gW10KICAgIGZvciBpdGVtIGluIHJvd3M6CiAgICAgICAgeCA9IGl0ZW1bInJvdyJdCiAgICAgICAgcmF3ID0geFsicmF3X3RleHQiXQogICAgICAgIHRydXRoID0gewogICAgICAgICAgICAiY2xhc3MiOiBpdGVtWyJ0cnV0aCJdWzBdLAogICAgICAgICAgICAidHJhbnNhY3Rpb24iOiBpdGVtWyJ0cnV0aCJdWzFdLAogICAgICAgICAgICAib3duZXJzaGlwIjogaXRlbVsidHJ1dGgiXVsyXSwKICAgICAgICB9CiAgICAgICAgc3R1ZGVudCA9IHY0MzQucHJlZGljdF9tZXNzYWdlKHJhdykKICAgICAgICBtaXNtYXRjaGVzID0gW10KICAgICAgICBmb3IgZmllbGQgaW4gKCJjbGFzcyIsICJ0cmFuc2FjdGlvbiIsICJvd25lcnNoaXAiKToKICAgICAgICAgICAgaWYgc3R1ZGVudFtmaWVsZF0gIT0gdHJ1dGhbZmllbGRdOgogICAgICAgICAgICAgICAgbWlzbWF0Y2hlcy5hcHBlbmQoewogICAgICAgICAgICAgICAgICAgICJmaWVsZCI6IGZpZWxkLAogICAgICAgICAgICAgICAgICAgICJ0cnV0aCI6IHRydXRoW2ZpZWxkXSwKICAgICAgICAgICAgICAgICAgICAic3R1ZGVudCI6IHN0dWRlbnRbZmllbGRdLAogICAgICAgICAgICAgICAgICAgICJmYW1pbHkiOiBfZmFpbHVyZV9mYW1pbHkoZmllbGQsIHRydXRoW2ZpZWxkXSwgc3R1ZGVudFtmaWVsZF0pLAogICAgICAgICAgICAgICAgfSkKICAgICAgICBpZiBub3QgbWlzbWF0Y2hlczoKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgZmlyc3RfY2xhdXNlID0gdjQzNC5fZmlyc3RfY2xhdXNlKHJhdykKICAgICAgICBkZW1hbmRfZmlyc3QgPSB2NDM0Ll9kZW1hbmRfZmlyc3QocmF3KQogICAgICAgIGRpcmVjdF9yZW50ID0gdjQzNC5fZGlyZWN0X3JlbnRfcmVxdWlyZW1lbnQocmF3KQogICAgICAgIG9mZmVyID0gdjQzNC5fZXhwbGljaXRfb2ZmZXJfYW5jaG9ycyhyYXcpCiAgICAgICAgcmVxNDMzLCBvZmZlcjQzMyA9IHY0MzMuX3JlcXVpcmVtZW50X2dyYW1tYXIocmF3KQogICAgICAgIHNyNDMzLCBzcDQzMywgY2xhdXNlczQzMyA9IHY0MzMuX3N0cmljdF9yZXF1aXJlbWVudF90eChyYXcpCiAgICAgICAgcmY0MzEgPSB2NDMxLl9yZXBhaXJfZmVhdHVyZXMocmF3KQogICAgICAgIG1peGVkLCBzYWxlX2hlYWRlcnMsIHJlbnRfaGVhZGVycyA9IHY0MzIuX21peGVkX3BhcmVudChyYXcpCgogICAgICAgIGZhaWx1cmVzLmFwcGVuZCh7CiAgICAgICAgICAgICJvcmRpbmFsIjogeFsib3JkaW5hbCJdLAogICAgICAgICAgICAiYXVkaXRfaWQiOiBzdHIoeFsiYXVkaXRfaWQiXSksCiAgICAgICAgICAgICJibGluZF9pZCI6IHN0cih4WyJibGluZF9pZCJdKSwKICAgICAgICAgICAgInRydXRoX3NvdXJjZSI6IGl0ZW0uZ2V0KCJ0cnV0aF9zb3VyY2UiKSwKICAgICAgICAgICAgInJhd190ZXh0IjogcmF3LAogICAgICAgICAgICAidHJ1dGgiOiB0cnV0aCwKICAgICAgICAgICAgInN0dWRlbnRfdjQzNCI6IHsKICAgICAgICAgICAgICAgICJjbGFzcyI6IHN0dWRlbnRbImNsYXNzIl0sCiAgICAgICAgICAgICAgICAidHJhbnNhY3Rpb24iOiBzdHVkZW50WyJ0cmFuc2FjdGlvbiJdLAogICAgICAgICAgICAgICAgIm93bmVyc2hpcCI6IHN0dWRlbnRbIm93bmVyc2hpcCJdLAogICAgICAgICAgICAgICAgImNvbmZpZGVuY2UiOiBzdHVkZW50LmdldCgiY29uZmlkZW5jZSIpLAogICAgICAgICAgICAgICAgInJ1bGUiOiBzdHVkZW50LmdldCgicnVsZSIpLAogICAgICAgICAgICB9LAogICAgICAgICAgICAibWlzbWF0Y2hlcyI6IG1pc21hdGNoZXMsCiAgICAgICAgICAgICJsYXllcnMiOiB7CiAgICAgICAgICAgICAgICAidjQwMiI6IF9wcmVkKHY0MDIucHJlZGljdF9tZXNzYWdlLCByYXcpLAogICAgICAgICAgICAgICAgInY0MzAiOiBfcHJlZCh2NDMwLnByZWRpY3RfbWVzc2FnZSwgcmF3KSwKICAgICAgICAgICAgICAgICJ2NDMxIjogX3ByZWQodjQzMS5wcmVkaWN0X21lc3NhZ2UsIHJhdyksCiAgICAgICAgICAgICAgICAidjQzMiI6IF9wcmVkKHY0MzIucHJlZGljdF9tZXNzYWdlLCByYXcpLAogICAgICAgICAgICAgICAgInY0MzMiOiBfcHJlZCh2NDMzLnByZWRpY3RfbWVzc2FnZSwgcmF3KSwKICAgICAgICAgICAgICAgICJ2NDM0IjogX3ByZWQodjQzNC5wcmVkaWN0X21lc3NhZ2UsIHJhdyksCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJmb3JlbnNpY19mZWF0dXJlcyI6IHsKICAgICAgICAgICAgICAgICJmaXJzdF9jbGF1c2UiOiBmaXJzdF9jbGF1c2UsCiAgICAgICAgICAgICAgICAidjQzNF9kZW1hbmRfZmlyc3QiOiBkZW1hbmRfZmlyc3QsCiAgICAgICAgICAgICAgICAidjQzNF9kaXJlY3RfcmVudF9yZXF1aXJlbWVudCI6IGRpcmVjdF9yZW50LAogICAgICAgICAgICAgICAgInY0MzRfZXhwbGljaXRfb2ZmZXJfYW5jaG9yc19hbnl3aGVyZSI6IG9mZmVyLAogICAgICAgICAgICAgICAgInY0MzNfcmVxdWlyZW1lbnRfZ3JhbW1hcl9hbnl3aGVyZSI6IHJlcTQzMywKICAgICAgICAgICAgICAgICJ2NDMzX29mZmVyX2dyYW1tYXJfYW55d2hlcmUiOiBvZmZlcjQzMywKICAgICAgICAgICAgICAgICJ2NDMzX3N0cm9uZ19yZW50X3NhbWVfY2xhdXNlIjogc3I0MzMsCiAgICAgICAgICAgICAgICAidjQzM19zdHJvbmdfcHVyY2hhc2Vfc2FtZV9jbGF1c2UiOiBzcDQzMywKICAgICAgICAgICAgICAgICJ2NDMzX2NsYXVzZXMiOiBjbGF1c2VzNDMzLAogICAgICAgICAgICAgICAgInY0MzFfcmVwYWlyX2ZlYXR1cmVzIjogcmY0MzEsCiAgICAgICAgICAgICAgICAidjQzMl9taXhlZF9wYXJlbnQiOiB7CiAgICAgICAgICAgICAgICAgICAgIm1peGVkIjogbWl4ZWQsCiAgICAgICAgICAgICAgICAgICAgInNhbGVfaGVhZGVycyI6IHNhbGVfaGVhZGVycywKICAgICAgICAgICAgICAgICAgICAicmVudF9oZWFkZXJzIjogcmVudF9oZWFkZXJzLAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgfSwKICAgICAgICB9KQoKICAgIHJldHVybiB7CiAgICAgICAgInZlcnNpb24iOiBWRVJTSU9OLAogICAgICAgICJtb2RlIjogTU9ERSwKICAgICAgICAidG90YWxfdjRfdHJ1dGhfY2FzZXMiOiBsZW4ocm93cyksCiAgICAgICAgImZhaWx1cmVfY2FzZXMiOiBsZW4oZmFpbHVyZXMpLAogICAgICAgICJmYWlsdXJlcyI6IGZhaWx1cmVzLAogICAgICAgICJkaWFnbm9zdGljX3BvbGljeSI6ICgKICAgICAgICAgICAgIlJlYWQtb25seS4gRXhhY3QgZnJvemVuIFY0IHRydXRoIGlzIGNvbXBhcmVkIHdpdGggZWFjaCBzdHVkZW50IGxheWVyLiAiCiAgICAgICAgICAgICJObyBzdHVkZW50IHJ1bGUgaXMgY2hhbmdlZCwgbm8gVjUgY2FzZSBpcyBzZWxlY3RlZC9mcm96ZW4sIGFuZCBubyBHb2xkL3Byb2R1Y3Rpb24vV2hhdHNBcHAgd3JpdGUgb2NjdXJzLiIKICAgICAgICApLAogICAgICAgICJuZXh0X3N0ZXAiOiAoCiAgICAgICAgICAgICJVc2UgdGhpcyBwYWNrZXQgdG8gYnVpbGQgb25lIGdlbmVyaWMgcmVsYXRpb24vb3duZXJzaGlwIHJlcGFpci4gIgogICAgICAgICAgICAiRG8gbm90IHBhdGNoIGZyb20gYWdncmVnYXRlIHNjb3JlcyBhbG9uZS4iCiAgICAgICAgKSwKICAgICAgICAic2FmZXR5IjogewogICAgICAgICAgICAic3R1ZGVudF90dW5pbmciOiAwLAogICAgICAgICAgICAidjVfZnJlZXplIjogMCwKICAgICAgICAgICAgInByb2R1Y3Rpb25fd3JpdGVzIjogMCwKICAgICAgICAgICAgIndoYXRzYXBwX3dyaXRlcyI6IDAsCiAgICAgICAgICAgICJnb2xkX211dGF0aW9ucyI6IDAsCiAgICAgICAgfSwKICAgIH0KCmRlZiBfZGFzaGJvYXJkKGVuZ2luZSk6CiAgICBzID0gcmVwb3J0KGVuZ2luZSkKICAgIHJldHVybiBmIiIiPCFkb2N0eXBlIGh0bWw+PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0ndXRmLTgnPgogICAgPHRpdGxlPkFsbGlhbmNlIFY0IEZhaWx1cmUgRm9yZW5zaWNzIDQuMy40RjwvdGl0bGU+CiAgICA8c3R5bGU+CiAgICAgIGJvZHl7e2ZvbnQtZmFtaWx5OkFyaWFsO21hcmdpbjozMHB4O2JhY2tncm91bmQ6I2Y2ZjdmYjtjb2xvcjojMTcyMDMzO21heC13aWR0aDoxMjUwcHh9fQogICAgICAuZ3JpZHt7ZGlzcGxheTpncmlkO2dyaWQtdGVtcGxhdGUtY29sdW1uczpyZXBlYXQoYXV0by1maXQsbWlubWF4KDE4MHB4LDFmcikpO2dhcDoxMnB4fX0KICAgICAgLmNhcmR7e2JhY2tncm91bmQ6I2ZmZjtwYWRkaW5nOjE4cHg7Ym9yZGVyLXJhZGl1czoxNHB4O2JveC1zaGFkb3c6MCAycHggMTBweCAjMDAwMX19CiAgICAgIHN0cm9uZ3t7ZGlzcGxheTpibG9jaztmb250LXNpemU6MjVweDttYXJnaW4tdG9wOjhweH19CiAgICAgIC5va3t7YmFja2dyb3VuZDojZThmOGVlO3BhZGRpbmc6MTZweDtib3JkZXItcmFkaXVzOjEwcHg7Zm9udC13ZWlnaHQ6NzAwO21hcmdpbjoxOHB4IDB9fQogICAgICBwcmV7e3doaXRlLXNwYWNlOnByZS13cmFwO2JhY2tncm91bmQ6IzEwMTYyNDtjb2xvcjojZWVmM2ZmO3BhZGRpbmc6MTZweDtib3JkZXItcmFkaXVzOjEwcHg7bGluZS1oZWlnaHQ6MS40fX0KICAgIDwvc3R5bGU+PC9oZWFkPjxib2R5PgogICAgPGgxPkFsbGlhbmNlIFY0IEZhaWx1cmUgRm9yZW5zaWNzIDQuMy40RjwvaDE+CiAgICA8cD5FeGFjdCBmcm96ZW4gVjQgZmFpbHVyZXMgd2l0aCByYXcgdGV4dCwgdHJ1dGgsIGV2ZXJ5IHN0dWRlbnQgbGF5ZXIsIGNsYXVzZSBzcGxpdHMgYW5kIHJlbGF0aW9uIHNpZ25hbHMuIFJlYWQtb25seSBkaWFnbm9zdGljIG9ubHkuPC9wPgogICAgPGRpdiBjbGFzcz0nZ3JpZCc+CiAgICAgIDxkaXYgY2xhc3M9J2NhcmQnPlY0IFRydXRoIENhc2VzPHN0cm9uZz57c1sndG90YWxfdjRfdHJ1dGhfY2FzZXMnXX08L3N0cm9uZz48L2Rpdj4KICAgICAgPGRpdiBjbGFzcz0nY2FyZCc+RXhhY3QgRmFpbHVyZXM8c3Ryb25nPntzWydmYWlsdXJlX2Nhc2VzJ119PC9zdHJvbmc+PC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9J2NhcmQnPlN0dWRlbnQgQ2hhbmdlczxzdHJvbmc+MDwvc3Ryb25nPjwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSdjYXJkJz5WNSBGcm96ZW48c3Ryb25nPjA8L3N0cm9uZz48L2Rpdj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0nb2snPk5vIG5ldyBzdHVkZW50IHBhdGNoIGlzIGJlaW5nIGd1ZXNzZWQgZnJvbSBhZ2dyZWdhdGUgc2NvcmVzLiBWNSByZW1haW5zIHVudG91Y2hlZC48L2Rpdj4KICAgIDxoMj5NYWNoaW5lIEZvcmVuc2ljIFBhY2tldDwvaDI+CiAgICA8cHJlPntodG1sLmVzY2FwZShqc29uLmR1bXBzKF9zYWZlKHMpLCBlbnN1cmVfYXNjaWk9RmFsc2UsIGluZGVudD0yKSl9PC9wcmU+CiAgICA8L2JvZHk+PC9odG1sPiIiIgoKZGVmIHJlZ2lzdGVyKGNvcmUpOgogICAgZW5naW5lID0gX2VuZ2luZShjb3JlKQogICAgYXBwID0gX2FwcChjb3JlKQoKICAgIGlmIG5vdCBmb3VuZGF0aW9uLl9yb3V0ZV9leGlzdHMoYXBwLCAiL2FwaS9wcm9wZXJ0eS1icmFpbi9hdXRvbm9tb3VzLXY0MzQtZm9yZW5zaWNzL3N0YXR1cyIpOgogICAgICAgIEBhcHAuZ2V0KCIvYXBpL3Byb3BlcnR5LWJyYWluL2F1dG9ub21vdXMtdjQzNC1mb3JlbnNpY3Mvc3RhdHVzIikKICAgICAgICBkZWYgc3RhdHVzX3Y0MzRfZm9yZW5zaWNzKCk6CiAgICAgICAgICAgIHJldHVybiByZXBvcnQoZW5naW5lKQoKICAgIGlmIG5vdCBmb3VuZGF0aW9uLl9yb3V0ZV9leGlzdHMoYXBwLCAiL3Byb3BlcnR5LWJyYWluL2F1dG9ub21vdXMtdjQzNC1mb3JlbnNpY3MiKToKICAgICAgICBAYXBwLmdldCgiL3Byb3BlcnR5LWJyYWluL2F1dG9ub21vdXMtdjQzNC1mb3JlbnNpY3MiLCByZXNwb25zZV9jbGFzcz1IVE1MUmVzcG9uc2UpCiAgICAgICAgZGVmIHBhZ2VfdjQzNF9mb3JlbnNpY3MoKToKICAgICAgICAgICAgcmV0dXJuIEhUTUxSZXNwb25zZShfZGFzaGJvYXJkKGVuZ2luZSkpCgogICAgcmV0dXJuIHsKICAgICAgICAic3RhdHVzIjogIlJFR0lTVEVSRUQiLAogICAgICAgICJ2ZXJzaW9uIjogVkVSU0lPTiwKICAgICAgICAicm91dGUiOiAiL3Byb3BlcnR5LWJyYWluL2F1dG9ub21vdXMtdjQzNC1mb3JlbnNpY3MiLAogICAgICAgICJzdHVkZW50X3R1bmluZyI6IDAsCiAgICAgICAgInY1X2ZyZWV6ZSI6IDAsCiAgICAgICAgInByb2R1Y3Rpb25fd3JpdGVzIjogMCwKICAgICAgICAid2hhdHNhcHBfd3JpdGVzIjogMCwKICAgICAgICAiZ29sZF9tdXRhdGlvbnMiOiAwLAogICAgfQo="

def chk(p):
    compile(p.read_text(encoding="utf-8"), str(p), "exec")

def main():
    r=Path.cwd()
    required=[
        "alliance_autonomous_student_v434.py",
        "alliance_autonomous_student_v433.py",
        "alliance_autonomous_student_v432.py",
        "alliance_autonomous_student_v431.py",
        "alliance_autonomous_student_v430.py",
        "alliance_cre_academy_v402.py",
        REG,
    ]
    missing=[x for x in required if not (r/x).exists()]
    if missing:
        raise SystemExit("Missing cumulative files: "+", ".join(missing))

    v434=(r/"alliance_autonomous_student_v434.py").read_text(encoding="utf-8")
    for marker in [
        'VERSION = "4.3.4-ALLIANCE-AUTONOMOUS-STUDENT-V5-DEMAND-OWNERSHIP-CLOSURE"',
        "V434_TRAINING_HOLD_DO_NOT_FREEZE_V5",
        "V434_DEMAND_FIRST_CLASS_OWNERSHIP",
    ]:
        if marker not in v434:
            raise SystemExit("Current 4.3.4 source differs; refusing blind forensic install: "+marker)

    reg=r/REG
    old=reg.read_text(encoding="utf-8")
    bak=r/f"{REG}.before-v434f-{datetime.now().strftime('%Y%m%d-%H%M%S')}.bak"
    shutil.copy2(reg,bak)

    (r/MODULE).write_text(base64.b64decode(DATA).decode(), encoding="utf-8")

    marker="# FOUNDATION 4.3.4F - Exact V4 Failure Forensics"
    if marker not in old:
        pos=old.rfind("    return result")
        if pos<0:
            raise SystemExit("Registrar return not found; no changes made.")
        block=r"""
    # FOUNDATION 4.3.4F - Exact V4 Failure Forensics
    # Read-only forensic route. No student changes. No V5 freeze.
    try:
        if _route_exists(app, "/api/property-brain/autonomous-v434-forensics/status"):
            result["v434_forensics"] = {"status":"ALREADY_REGISTERED","route":"/property-brain/autonomous-v434-forensics","error":None}
        else:
            import alliance_v4_failure_forensics_v434f as v434_forensics
            result["v434_forensics"] = {**v434_forensics.register(core), "error": None}
    except Exception as exc:
        result["v434_forensics"] = {"status":"ERROR","error":f"{type(exc).__name__}: {exc}","route":"/property-brain/autonomous-v434-forensics","fail_safe":True}

"""
        reg.write_text(old[:pos]+block+old[pos:], encoding="utf-8")

    chk(r/MODULE)
    chk(reg)

    txt=reg.read_text(encoding="utf-8")
    checks={
        "v430":"autonomous_v430" in txt,
        "v431":"autonomous_v431" in txt,
        "v432":"autonomous_v432" in txt,
        "v433":"autonomous_v433" in txt,
        "v434":"autonomous_v434" in txt,
        "v434f":"v434_forensics" in txt,
    }
    if not all(checks.values()):
        raise SystemExit("Cumulative verification failed: "+repr(checks))

    print("Alliance V4 Failure Forensics 4.3.4F installed")
    print("Student changes: 0")
    print("V5 freeze: 0")
    print("Production/WhatsApp/Gold writes: 0")
    print("Dashboard: /property-brain/autonomous-v434-forensics")
    print("Backup:", bak)

if __name__=="__main__":
    main()
