from __future__ import annotations
import base64, shutil
from datetime import datetime
from pathlib import Path

TARGET="alliance_exception_forensics_v424.py"
REG="alliance_optional_property_modules.py"
DATA="ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwppbXBvcnQgaHRtbCwganNvbgpmcm9tIGZhc3RhcGkucmVzcG9uc2VzIGltcG9ydCBIVE1MUmVzcG9uc2UKZnJvbSBzcWxhbGNoZW15IGltcG9ydCB0ZXh0CgppbXBvcnQgYWxsaWFuY2VfcHJvcGVydHlfYnJhaW5fZm91bmRhdGlvbl92MSBhcyBmb3VuZGF0aW9uCmltcG9ydCBhbGxpYW5jZV9jcmVfY2hhbXBpb25zaGlwX3Y0MTAgYXMgdjQxMAppbXBvcnQgYWxsaWFuY2VfYXV0b21hdGlvbl90cnV0aF9lc2NhbGF0b3JfdjQyMSBhcyB2NDIxCmltcG9ydCBhbGxpYW5jZV9hdXRvbWF0aW9uX2Nsb3N1cmVfdjQyMiBhcyB2NDIyCmltcG9ydCBhbGxpYW5jZV9hdXRvbWF0aW9uX2dyYW1tYXJfcmVzY3VlX3Y0MjMgYXMgdjQyMwoKVkVSU0lPTj0iNC4yLjQuMi1BTExJQU5DRS1FWENFUFRJT04tRk9SRU5TSUNTLUhPVEZJWCIKTU9ERT0iUkVBRF9PTkxZX0ZPUkVOU0lDU19BUElfSE9URklYX1Y0MjFfSU5URVJOQUxfSlVER0VfUkVHSVNUUlkiCkVYQU1fVkVSU0lPTj12NDEwLkVYQU1fVkVSU0lPTgoKZGVmIF9lbmdpbmUoY29yZSk6IHJldHVybiBmb3VuZGF0aW9uLl9lbmdpbmVfZnJvbV9jb3JlKGNvcmUpCmRlZiBfYXBwKGNvcmUpOiByZXR1cm4gZ2V0YXR0cihjb3JlLCJhcHAiLE5vbmUpIG9yIGNvcmUKCmRlZiBpbnNwZWN0KGVuZ2luZSk6CiAgICB2NDIzLnJ1bihlbmdpbmUpCiAgICB3aXRoIGVuZ2luZS5jb25uZWN0KCkgYXMgYzoKICAgICAgICByb3dzPVtkaWN0KHIpIGZvciByIGluIGMuZXhlY3V0ZSh0ZXh0KCIiIgogICAgICAgIFNFTEVDVCBjLmF1ZGl0X2lkLGMub3JkaW5hbCxjLnJhd190ZXh0LAogICAgICAgICAgICAgICBjLnByZWRpY3RlZF9jbGFzcyxjLnByZWRpY3RlZF90cmFuc2FjdGlvbixjLnByZWRpY3RlZF9vd25lcnNoaXAsCiAgICAgICAgICAgICAgIGMucHJlZGljdGlvbl9jb25maWRlbmNlLGMucHJlZGljdGlvbl9ydWxlLAogICAgICAgICAgICAgICBhLnN0YXR1cyBhX3N0YXR1cyxhLnRydXRoX2NsYXNzIGFfY2xhc3MsYS50cnV0aF90cmFuc2FjdGlvbiBhX3R4LGEudHJ1dGhfb3duZXJzaGlwIGFfb3duLGEuY29uc2Vuc3VzIGFfZXZpZGVuY2UsCiAgICAgICAgICAgICAgIHouc3RhdHVzIHpfc3RhdHVzLHoudHJ1dGhfY2xhc3Mgel9jbGFzcyx6LnRydXRoX3RyYW5zYWN0aW9uIHpfdHgsei50cnV0aF9vd25lcnNoaXAgel9vd24sei5ldmlkZW5jZSB6X2V2aWRlbmNlLAogICAgICAgICAgICAgICByLnN0YXR1cyByX3N0YXR1cyxyLnRydXRoX2NsYXNzIHJfY2xhc3Msci50cnV0aF90cmFuc2FjdGlvbiByX3R4LHIudHJ1dGhfb3duZXJzaGlwIHJfb3duLHIuZXZpZGVuY2Ugcl9ldmlkZW5jZQogICAgICAgIEZST00gYWxsaWFuY2VfY2hhbXBpb25zaGlwX3Y0MTBfY2FzZXMgYwogICAgICAgIExFRlQgSk9JTiBhbGxpYW5jZV9hdXRvbWF0aW9uX3Y0MjFfdHJ1dGggYSBPTiBhLmF1ZGl0X2lkPWMuYXVkaXRfaWQKICAgICAgICBMRUZUIEpPSU4gYWxsaWFuY2VfYXV0b21hdGlvbl92NDIyX3RydXRoIHogT04gei5hdWRpdF9pZD1jLmF1ZGl0X2lkCiAgICAgICAgTEVGVCBKT0lOIGFsbGlhbmNlX2F1dG9tYXRpb25fdjQyM190cnV0aCByIE9OIHIuYXVkaXRfaWQ9Yy5hdWRpdF9pZAogICAgICAgIFdIRVJFIGMuZXhhbV92ZXJzaW9uPTplCiAgICAgICAgT1JERVIgQlkgYy5vcmRpbmFsCiAgICAgICAgIiIiKSx7ImUiOkVYQU1fVkVSU0lPTn0pLm1hcHBpbmdzKCldCiAgICB1bnJlc29sdmVkPVtdCiAgICBmb3IgeCBpbiByb3dzOgogICAgICAgIGlmIHhbImFfc3RhdHVzIl09PSJBVVRPX1JFU09MVkVEIiBvciB4WyJ6X3N0YXR1cyJdPT0iQVVUT19SRVNPTFZFRCIgb3IgeFsicl9zdGF0dXMiXT09IkFVVE9fUkVTT0xWRUQiOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIHJhdz14WyJyYXdfdGV4dCJdIG9yICIiCiAgICAgICAgdW5yZXNvbHZlZC5hcHBlbmQoewogICAgICAgICAgICAiYXVkaXRfaWQiOnN0cih4WyJhdWRpdF9pZCJdKSwKICAgICAgICAgICAgIm9yZGluYWwiOnhbIm9yZGluYWwiXSwKICAgICAgICAgICAgInJhd190ZXh0IjpyYXcsCiAgICAgICAgICAgICJzdHVkZW50X2Zyb3plbl9wcmVkaWN0aW9uIjp7CiAgICAgICAgICAgICAgICAiY2xhc3MiOnhbInByZWRpY3RlZF9jbGFzcyJdLAogICAgICAgICAgICAgICAgInRyYW5zYWN0aW9uIjp4WyJwcmVkaWN0ZWRfdHJhbnNhY3Rpb24iXSwKICAgICAgICAgICAgICAgICJvd25lcnNoaXAiOnhbInByZWRpY3RlZF9vd25lcnNoaXAiXSwKICAgICAgICAgICAgICAgICJjb25maWRlbmNlIjpmbG9hdCh4WyJwcmVkaWN0aW9uX2NvbmZpZGVuY2UiXSBvciAwKSwKICAgICAgICAgICAgICAgICJydWxlIjp4WyJwcmVkaWN0aW9uX3J1bGUiXSwKICAgICAgICAgICAgfSwKICAgICAgICAgICAgInY0MjEiOnsKICAgICAgICAgICAgICAgICJzdGF0dXMiOnhbImFfc3RhdHVzIl0sCiAgICAgICAgICAgICAgICAidHJ1dGgiOlt4WyJhX2NsYXNzIl0seFsiYV90eCJdLHhbImFfb3duIl0sCiAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAgImV2aWRlbmNlIjp4WyJhX2V2aWRlbmNlIl0sCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJ2NDIyIjp7CiAgICAgICAgICAgICAgICAic3RhdHVzIjp4WyJ6X3N0YXR1cyJdLAogICAgICAgICAgICAgICAgInRydXRoIjpbeFsiel9jbGFzcyJdLHhbInpfdHgiXSx4WyJ6X293biJdXSwKICAgICAgICAgICAgICAgICJldmlkZW5jZSI6eFsiel9ldmlkZW5jZSJdLAogICAgICAgICAgICB9LAogICAgICAgICAgICAidjQyMyI6ewogICAgICAgICAgICAgICAgInN0YXR1cyI6eFsicl9zdGF0dXMiXSwKICAgICAgICAgICAgICAgICJ0cnV0aCI6W3hbInJfY2xhc3MiXSx4WyJyX3R4Il0seFsicl9vd24iXV0sCiAgICAgICAgICAgICAgICAiZXZpZGVuY2UiOnhbInJfZXZpZGVuY2UiXSwKICAgICAgICAgICAgfSwKICAgICAgICAgICAgImZyZXNoX2RpYWdub3N0aWNzIjp7CiAgICAgICAgICAgICAgICAidjQyMV9hbGxfanVkZ2VzIjp2NDIxLl9qdWRnZXMoZW5naW5lLHJhdyksCiAgICAgICAgICAgICAgICAidjQyMl9zZW1hbnRpY190cnV0aCI6djQyMi5zZW1hbnRpY190cnV0aChyYXcpLAogICAgICAgICAgICAgICAgInY0MjNfZ3JhbW1hcl9qdWRnZV9vbmUiOnY0MjMuZ3JhbW1hcl9qdWRnZV9vbmUocmF3KSwKICAgICAgICAgICAgICAgICJ2NDIzX2dyYW1tYXJfanVkZ2VfdHdvIjp2NDIzLmdyYW1tYXJfanVkZ2VfdHdvKHJhdyksCiAgICAgICAgICAgICAgICAidjQyM19yZXNjdWVfdHJ1dGgiOnY0MjMucmVzY3VlX3RydXRoKHJhdyksCiAgICAgICAgICAgIH0KICAgICAgICB9KQogICAgcmV0dXJuIHsKICAgICAgICAidmVyc2lvbiI6VkVSU0lPTiwKICAgICAgICAiZXhhbV92ZXJzaW9uIjpFWEFNX1ZFUlNJT04sCiAgICAgICAgInVucmVzb2x2ZWRfY291bnQiOmxlbih1bnJlc29sdmVkKSwKICAgICAgICAiY2FzZXMiOmZvdW5kYXRpb24uX2pzb25fc2FmZSh1bnJlc29sdmVkKSwKICAgICAgICAibmV4dF9zdGVwIjoiVXNlIHRoaXMgcmVhZC1vbmx5IGZvcmVuc2ljIHBhY2tldCB0byBidWlsZCBhIGdlbmVyaWMgYXV0b21hdGVkIHJlc29sdmVyLiBEbyBub3QgbWFudWFsbHkgbGFiZWwgdGhlIGNhc2UuIiwKICAgICAgICAic2FmZXR5Ijp7InN0dWRlbnRfdHVuaW5nIjowLCJwcm9kdWN0aW9uX3dyaXRlcyI6MCwid2hhdHNhcHBfd3JpdGVzIjowLCJnb2xkX211dGF0aW9ucyI6MH0KICAgIH0KCmRlZiBfZGFzaGJvYXJkKGVuZ2luZSk6CiAgICBkYXRhPWluc3BlY3QoZW5naW5lKQogICAgcmV0dXJuIGYiIiI8IWRvY3R5cGUgaHRtbD48aHRtbD48aGVhZD48bWV0YSBjaGFyc2V0PSd1dGYtOCc+CiAgICA8dGl0bGU+QWxsaWFuY2UgRXhjZXB0aW9uIEZvcmVuc2ljcyA0LjIuNDwvdGl0bGU+CiAgICA8c3R5bGU+Ym9keXt7Zm9udC1mYW1pbHk6QXJpYWw7bWFyZ2luOjMwcHg7YmFja2dyb3VuZDojZjZmN2ZiO2NvbG9yOiMxNzIwMzM7bWF4LXdpZHRoOjEyMDBweH19cHJle3t3aGl0ZS1zcGFjZTpwcmUtd3JhcDtiYWNrZ3JvdW5kOiMxMDE2MjQ7Y29sb3I6I2VlZjNmZjtwYWRkaW5nOjE4cHg7Ym9yZGVyLXJhZGl1czoxMnB4fX0ub2t7e2JhY2tncm91bmQ6I2U4ZjhlZTtwYWRkaW5nOjE0cHg7Ym9yZGVyLXJhZGl1czoxMHB4fX08L3N0eWxlPjwvaGVhZD48Ym9keT4KICAgIDxoMT5BbGxpYW5jZSBFeGNlcHRpb24gRm9yZW5zaWNzIDQuMi40PC9oMT4KICAgIDxwPlJlYWQtb25seSBmb3JlbnNpYyBwYWNrZXQgZm9yIG9ubHkgdGhlIGZpbmFsIHVucmVzb2x2ZWQgVjQgY2FzZShzKS4gRnJvemVuIHN0dWRlbnQgcmVtYWlucyB1bnRvdWNoZWQuPC9wPgogICAgPGRpdiBjbGFzcz0nb2snPlVucmVzb2x2ZWQgY2FzZXM6IDxiPntkYXRhWyJ1bnJlc29sdmVkX2NvdW50Il19PC9iPi4gTm8gbWFudWFsIGNsYXNzaWZpY2F0aW9uIHJlcXVlc3RlZC48L2Rpdj4KICAgIDxoMj5NYWNoaW5lIEZvcmVuc2ljIFJlcG9ydDwvaDI+CiAgICA8cHJlPntodG1sLmVzY2FwZShqc29uLmR1bXBzKGRhdGEsZW5zdXJlX2FzY2lpPUZhbHNlLGluZGVudD0yKSl9PC9wcmU+CiAgICA8L2JvZHk+PC9odG1sPiIiIgoKZGVmIHJlZ2lzdGVyKGNvcmUpOgogICAgZW5naW5lPV9lbmdpbmUoY29yZSk7IGFwcD1fYXBwKGNvcmUpCiAgICBpZiBub3QgZm91bmRhdGlvbi5fcm91dGVfZXhpc3RzKGFwcCwiL2FwaS9wcm9wZXJ0eS1icmFpbi9hdXRvbWF0aW9uLXY0MjQvc3RhdHVzIik6CiAgICAgICAgQGFwcC5nZXQoIi9hcGkvcHJvcGVydHktYnJhaW4vYXV0b21hdGlvbi12NDI0L3N0YXR1cyIpCiAgICAgICAgZGVmIHN0YXR1c192NDI0KCk6IHJldHVybiBpbnNwZWN0KGVuZ2luZSkKICAgIGlmIG5vdCBmb3VuZGF0aW9uLl9yb3V0ZV9leGlzdHMoYXBwLCIvcHJvcGVydHktYnJhaW4vYXV0b21hdGlvbi12NDI0Iik6CiAgICAgICAgQGFwcC5nZXQoIi9wcm9wZXJ0eS1icmFpbi9hdXRvbWF0aW9uLXY0MjQiLHJlc3BvbnNlX2NsYXNzPUhUTUxSZXNwb25zZSkKICAgICAgICBkZWYgcGFnZV92NDI0KCk6IHJldHVybiBIVE1MUmVzcG9uc2UoX2Rhc2hib2FyZChlbmdpbmUpKQogICAgcmV0dXJuIHsic3RhdHVzIjoiUkVHSVNURVJFRCIsInZlcnNpb24iOlZFUlNJT04sInJvdXRlIjoiL3Byb3BlcnR5LWJyYWluL2F1dG9tYXRpb24tdjQyNCIsCiAgICAgICAgICAgICJwb2xpY3kiOiJSRUFEX09OTFlfRVhDRVBUSU9OX0ZPUkVOU0lDUyIsInN0dWRlbnRfdHVuaW5nIjowLCJwcm9kdWN0aW9uX3dyaXRlcyI6MCwid2hhdHNhcHBfd3JpdGVzIjowLCJnb2xkX211dGF0aW9ucyI6MH0K"

def chk(p):
    compile(p.read_text(encoding="utf-8"), str(p), "exec")

def main():
    r=Path.cwd()
    required=[
        TARGET,
        "alliance_automation_grammar_rescue_v423.py",
        "alliance_automation_closure_v422.py",
        "alliance_automation_truth_escalator_v421.py",
        "alliance_automation_machine_v420.py",
        "alliance_cre_championship_v410.py",
        "alliance_cre_academy_v402.py",
        REG,
    ]
    missing=[x for x in required if not (r/x).exists()]
    if missing:
        raise SystemExit("Missing cumulative files: "+", ".join(missing))

    v421=(r/"alliance_automation_truth_escalator_v421.py").read_text(encoding="utf-8")
    required_symbols=["def _judges(","def judge_cre_graph(","def judge_intent_hierarchy(","v420.judge_evidence","v420.judge_critic"]
    absent=[s for s in required_symbols if s not in v421]
    if absent:
        raise SystemExit("Current v421 API differs; refusing blind update: "+repr(absent))

    current=(r/TARGET).read_text(encoding="utf-8")
    if "v421.judge_evidence(raw)" not in current and "v421._judges(engine,raw)" not in current:
        raise SystemExit("Unexpected v424 diagnostics shape; refusing blind overwrite.")

    backup=r/f"{TARGET}.before-hotfix2-{datetime.now().strftime('%Y%m%d-%H%M%S')}.bak"
    shutil.copy2(r/TARGET,backup)
    (r/TARGET).write_text(base64.b64decode(DATA).decode(),encoding="utf-8")

    chk(r/TARGET); chk(r/REG)

    final=(r/TARGET).read_text(encoding="utf-8")
    if "v421._judges(engine,raw)" not in final:
        raise SystemExit("4.2.4.2 verification failed.")
    if "v421.judge_evidence(raw)" in final:
        raise SystemExit("Obsolete v421 API call still present.")

    print("Foundation 4.2.4.2 hotfix installed")
    print("Fixed: forensic module now calls v421._judges(engine, raw)")
    print("Verified current v421 judge registry before replacement")
    print("Frozen V4 student unchanged")
    print("Production/WhatsApp/Gold writes: 0")
    print("Dashboard remains: /property-brain/automation-v424")
    print("Backup:",backup)

if __name__=="__main__":
    main()
